Booklet Repo/booklet_repository/booklet_repository/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from booklets import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup', views.CustomSignupView.as_view(), name='signup'),
    path('accounts/', include('allauth.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.CustomLogoutView.as_view(template_name='logout.html'), name='logout'),
    path('', views.booklet_list, name='signup'),
    path('booklets/', views.booklet_list, name='booklet_list'),
    path('upload/', views.upload_booklet, name='upload_booklet'),
    path('delete/<int:booklet_id>/', views.delete_booklet, name='delete_booklet'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Booklet Repo/booklet_repository/booklets/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Booklet(models.Model):
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='booklets/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

Booklet Repo/booklet_repository/booklets/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Booklet

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255, required=True, help_text="Required. Please Enter a valid email address.")

    class Meta:
        model = User    
        fields = ('username','email','password1','password2')

class BookletUploadForm(forms.ModelForm):
    class Meta:
        model = Booklet
        fields = ['title','file']


Booklet Repo/booklet_repository/booklets/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .forms import SignUpForm, BookletUploadForm
from .models import Booklet
from allauth.account.views import SignupView
from django.urls import reverse

# Create your views here.   
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('booklet_list')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('booklet_list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

@login_required
def booklet_list(request):
    if request.user.is_superuser:
        booklets = Booklet.objects.filter(author=request.user)
    else:
        booklets = Booklet.objects.all()
    return render(request, 'booklet_list.html',{'booklets':booklets})

@login_required
def upload_booklet(request):
    if request.method == 'POST':
        form = BookletUploadForm(request.POST, request.FILES)
        if form.is_valid():
            booklet = form.save(commit=False)
            booklet.author = request.user
            booklet.save()
            return redirect('booklet_list')
    else:
        form = BookletUploadForm()
    return render(request, 'upload_booklet.html', {'form': form})   

@login_required
def delete_booklet(request, booklet_id):
    booklet = Booklet.objects.get(id=booklet_id)
    if request.user.is_superuser and booklet.author == request.user:
        booklet.delete()
    return redirect('booklet_list')

class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CustomSignupView(SignupView):
    def get_success_url(self):
        return reverse('booklet_list')  


Booklet Repo/booklet_repository/booklets/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Booklet Repository</title>
        <link
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            rel="stylesheet"
        />
        <link href="../static/styles/styles.css" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Booklet Repository</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container mt-5">{% block content %} {% endblock %}</div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

Booklet Repo/booklet_repository/booklets/templates/booklet_list.html
{% extends 'base.html' %} {% comment %} <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Booklet List</title>
    </head>
    <body>
        <h2>Booklet List</h2>
        <a href="{% url 'account_logout' %}">Logout</a>
        <a href=""></a>
        {% if user.is_superuser %}
        <a href="{% url 'upload_booklet' %}">Add New Booklet</a>
        {% endif %}
        <ul>
            {% for booklet in booklets %}
            <li>
                {{ booklet.title }} - {{ booklet.uploaded_at }}
                <a href="{{ booklet.file.url }}" download>Download</a>
                {% if user.is_superuser %}
                <a href="{% url 'delete_booklet' booklet.id %}">Delete</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </body>
</html>
{% endcomment %} {% block content %}
<h2 class="text-center">Booklets</h2>
{% if user.is_superuser %}
<a href="{% url 'upload_booklet' %}" class="btn btn-primary">Add New Booklet</a>
{% endif %}
<div class="row">
    {% for booklet in booklets %}
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ booklet.title }}</h5>
                <p class="card-text">Uploaded on:  {{ booklet.uploaded_at }}</p>
                <a
                    href="{{ booklet.file.url }}"
                    class="btn btn-primary"
                    download
                    >Download</a
                >
                {% if user.is_authenticated and user.is_staff %}
                <form
                    method="post"
                    action="{% url 'delete_booklet' booklet.id %}"
                    class="mt-2"
                >
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-block">
                        Delete
                    </button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Booklet Repo/booklet_repository/booklets/templates/login.html
{% extends 'base.html' %} {% comment %} <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Login</title>
    </head>
    <body>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
        <a href="/signup">Signup</a>
    </body>
</html>
{% endcomment %} {% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">Login</h3>
                <form method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block">
                        Login
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Booklet Repo/booklet_repository/booklets/templates/signup.html
{% extends 'base.html' %} {% comment %} <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Signup</title>
    </head>
    <body>
        <h2>Signup</h2>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit">Signup</button>
        </form>
    </body>
</html>
{% endcomment %} {% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">Sign Up</h3>
                <form method="post" action="{% url 'account_signup' %}">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block">
                        Sign Up
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Booklet Repo/booklet_repository/booklets/templates/upload_booklet.html
{% extends "base.html" %} {% comment %} <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Upload Booklet</title>
    </head>
    <body>
        <h2>Upload Booklet</h2>
        {% if user.is_superuser%}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
        {% else %}
        <p>You are not authorized to upload booklets.</p>
        <a href="{% url 'booklet_list'%}">Booklet List</a>
        {% endif %}
    </body>
</html>
{% endcomment %} {% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">Upload New Booklet</h3>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title</label>
                        <input
                            type="text"
                            class="form-control"
                            id="id_title"
                            name="title"
                            required
                        />
                    </div>
                    <div class="form-group">
                        <label for="id_file">Upload PDF</label>
                        <input
                            type="file"
                            class="form-control-file"
                            id="id_file"
                            name="file"
                            accept="application/pdf"
                            required
                        />
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">
                        Upload
                    </button>
                </form>
                <div class="text-center mt-3">
                    <a href="{% url 'booklet_list' %}" class="btn btn-secondary"
                        >Back to Booklets</a
                    >
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}